INSERT IGNORE INTO permissoes_grupo (nome) VALUES ('ADMIN');
INSERT IGNORE INTO usuario_auth (username, password, role) VALUES ('admin@example.com', '$2b$10$dbqs8pL80Nb/xPZ6XTD2zu.1StJ7vu0AgynHl3v3s3E.cQ/Gc6LxG', 'ADMIN');
INSERT IGNORE INTO usuarios (nome, email, senha, permissao_grupo_id) VALUES ('Administrador', 'admin@example.com', '$2b$10$dbqs8pL80Nb/xPZ6XTD2zu.1StJ7vu0AgynHl3v3s3E.cQ/Gc6LxG', 1);

-- Permissões de Páginas
INSERT IGNORE INTO permissoes_pagina (id, nome, rota, metodo_http) VALUES
  (1, 'Usuários - Listar', '/usuarios', 'GET'),
  (2, 'Usuários - Criar', '/usuarios', 'POST'),
  (3, 'Usuários - Atualizar', '/usuarios', 'PUT'),
  (4, 'Usuários - Remover', '/usuarios', 'DELETE'),
  (5, 'Permissão Grupo - Listar', '/permissao', 'GET'),
  (6, 'Permissão Grupo - Criar', '/permissao', 'POST'),
  (7, 'Permissão Grupo - Atualizar', '/permissao', 'PUT'),
  (8, 'Permissão Grupo - Remover', '/permissao', 'DELETE'),
  (9, 'Permissão Página - Listar', '/paginas', 'GET'),
  (10, 'Permissão Página - Criar', '/paginas', 'POST'),
  (11, 'Permissão Página - Atualizar', '/paginas', 'PUT'),
  (12, 'Permissão Página - Remover', '/paginas', 'DELETE'),
  (13, 'Turmas - Listar', '/turmas', 'GET'),
  (14, 'Turmas - Criar', '/turmas', 'POST'),
  (15, 'Turmas - Atualizar', '/turmas', 'PUT'),
  (16, 'Turmas - Remover', '/turmas', 'DELETE'),
  (17, 'Alunos - Listar', '/alunos', 'GET'),
  (18, 'Alunos - Criar', '/alunos', 'POST'),
  (19, 'Alunos - Atualizar', '/alunos', 'PUT'),
  (20, 'Alunos - Remover', '/alunos', 'DELETE'),
  (21, 'Cargos - Listar', '/cargos', 'GET'),
  (22, 'Cargos - Criar', '/cargos', 'POST'),
  (23, 'Cargos - Atualizar', '/cargos', 'PUT'),
  (24, 'Cargos - Remover', '/cargos', 'DELETE'),
  (25, 'Disciplina - Listar', '/disciplinas', 'GET'),
  (26, 'Disciplina - Criar', '/disciplinas', 'POST'),
  (27, 'Disciplina - Atualizar', '/disciplinas', 'PUT'),
  (28, 'Disciplina - Remover', '/disciplinas', 'DELETE'),
  (29, 'Funcionários - Listar', '/funcionarios', 'GET'),
  (30, 'Funcionários - Criar', '/funcionarios', 'POST'),
  (31, 'Funcionários - Atualizar', '/funcionarios', 'PUT'),
  (32, 'Funcionários - Remover', '/funcionarios', 'DELETE'),
  (33, 'Matrículas - Listar', '/matriculas', 'GET'),
  (34, 'Matrículas - Criar', '/matriculas', 'POST'),
  (35, 'Matrículas - Atualizar', '/matriculas', 'PUT'),
  (36, 'Matrículas - Remover', '/matriculas', 'DELETE'),
  (37, 'Planos Pagamento - Listar', '/planos-pagamento', 'GET'),
  (38, 'Planos Pagamento - Criar', '/planos-pagamento', 'POST'),
  (39, 'Planos Pagamento - Atualizar', '/planos-pagamento', 'PUT'),
  (40, 'Planos Pagamento - Remover', '/planos-pagamento', 'DELETE'),
  (41, 'Parcelas - Listar', '/parcelas', 'GET'),
  (42, 'Parcelas - Criar', '/parcelas', 'POST'),
  (43, 'Parcelas - Atualizar', '/parcelas', 'PUT'),
  (44, 'Parcelas - Remover', '/parcelas', 'DELETE'),
  (45, 'Pagamentos - Listar', '/pagamentos', 'GET'),
  (46, 'Pagamentos - Criar', '/pagamentos', 'POST'),
  (47, 'Pagamentos - Atualizar', '/pagamentos', 'PUT'),
  (48, 'Pagamentos - Remover', '/pagamentos', 'DELETE'),
  (49, 'Receitas - Listar', '/receitas', 'GET'),
  (50, 'Receitas - Criar', '/receitas', 'POST'),
  (51, 'Receitas - Atualizar', '/receitas', 'PUT'),
  (52, 'Receitas - Remover', '/receitas', 'DELETE'),
  (53, 'Despesas - Listar', '/despesas', 'GET'),
  (54, 'Despesas - Criar', '/despesas', 'POST'),
  (55, 'Despesas - Atualizar', '/despesas', 'PUT'),
  (56, 'Despesas - Remover', '/despesas', 'DELETE'),
  (57, 'Caixa - Listar', '/lancamentos-financeiros', 'GET'),
  (58, 'Caixa - Criar', '/lancamentos-financeiros', 'POST'),
  (59, 'Caixa - Atualizar', '/lancamentos-financeiros', 'PUT'),
  (60, 'Caixa - Remover', '/lancamentos-financeiros', 'DELETE'),
  (61, 'Descontos - Listar', '/descontos', 'GET'),
  (62, 'Descontos - Criar', '/descontos', 'POST'),
  (63, 'Descontos - Atualizar', '/descontos', 'PUT'),
  (64, 'Descontos - Remover', '/descontos', 'DELETE'),
  (65, 'Login', '/api/login', 'POST'),
  (66, 'Professores - Listar', '/professores', 'GET'),
  (67, 'Professores - Criar', '/professores', 'POST'),
  (68, 'Professores - Atualizar', '/professores', 'PUT'),
  (69, 'Professores - Remover', '/professores', 'DELETE'),
  (70, 'Diário Classe - Listar', '/diario-classe', 'GET'),
  (71, 'Diário Classe - Criar', '/diario-classe', 'POST'),
  (72, 'Diário Classe - Atualizar', '/diario-classe', 'PUT'),
  (73, 'Diário Classe - Remover', '/diario-classe', 'DELETE'),
  (74, 'Diário Bordo - Listar', '/diario-bordo', 'GET'),
  (75, 'Diário Bordo - Criar', '/diario-bordo', 'POST'),
  (76, 'Diário Bordo - Atualizar', '/diario-bordo', 'PUT'),
  (77, 'Diário Bordo - Remover', '/diario-bordo', 'DELETE');

-- Vincula todas as páginas ao grupo ADMIN
INSERT IGNORE INTO grupo_paginas (grupo_id, pagina_id) VALUES
  (1,1),(1,2),(1,3),(1,4),(1,5),(1,6),(1,7),(1,8),(1,9),(1,10),
  (1,11),(1,12),(1,13),(1,14),(1,15),(1,16),(1,17),(1,18),(1,19),(1,20),
  (1,21),(1,22),(1,23),(1,24),(1,25),(1,26),(1,27),(1,28),
  (1,29),(1,30),(1,31),(1,32),
  (1,33),(1,34),(1,35),(1,36),
  (1,37),(1,38),(1,39),(1,40),
  (1,41),(1,42),(1,43),(1,44),
  (1,45),(1,46),(1,47),(1,48),
  (1,49),(1,50),(1,51),(1,52),
  (1,53),(1,54),(1,55),(1,56),
  (1,57),(1,58),(1,59),(1,60),
  (1,61),(1,62),(1,63),(1,64),
  (1,65),(1,66),(1,67),(1,68),
  (1,69),(1,70),(1,71),(1,72),
  (1,73),(1,74),(1,75),(1,76),
  (1,77);
